if !has('vim9script') ||  v:version < 900
  " Needs Vim version 9.0 and above
  finish
endif

vim9script

#g:mapleader = "\<Space>"
#g:maplocalleader = "\<Space>" # meant for certain file types
#map <BS> <Leader>
#g:mapleader = ','
g:maplocalleader = '\\'

# To make undercurl work in iterm2 (:h E436, :h t_Cs)
&t_Cs = "\e[4:3m"
&t_Ce = "\e[4:0m"

# 6=beam, 4=underline, 2=block
# &t_SI = "\e[6 q" #SI = INSERT mode
# &t_SR = "\e[4 q" #SR = REPLACE mode
# &t_EI = "\e[2 q" #EI = NORMAL mode (ALL ELSE)
#&t_Cs = "\e[4:3m" #undercurl
# Reset the cursor on start. After suspend-resume, cursor changes to beam even
# in normal mode. This will prevent that.
autocmd VimEnter,VimResume * silent execute '!echo -ne "\e[2 q"' | redraw!

# Format usin 'gq'. :h fo-table
set formatoptions=qjln
# autocmd FileType * setl formatoptions=qjlron

# Defaults
source $VIMRUNTIME/defaults.vim
# disable message from 'defaults.vim' when entering cmdwin
autocmd! vimHints

# Turn on listchars for Noname/scratch files and non-help files
# 'listchars' is not local to buffer, only local to window
#autocmd FileType * if &ft =~ '\v(help|markdown)' | setlocal listchars=eol:\ ,tab:\ \ ,trail:\  | else | setlocal listchars=eol:\ ,tab:\ \ ,trail:· | endif
#autocmd BufEnter * if &ft == null_string | setlocal listchars=eol:\ ,tab:\ \ ,trail:\  | endif
# autocmd BufEnter,FileType * :echom &ft expand('<amatch>') expand('<afile>') 'here'
set list
set listchars=eol:\ ,tab:\󰁕·,trail:· #,leadmultispace:\┊\ \ \ 
set fillchars=vert:│,fold:۰,diff:·,stl:─,stlnc:═,eob:\ 

set noshowcmd  # XXX: Stop echoing keymapped typed keys in the bottom row
set clipboard=unnamedplus # Always use the system clipboard
set mouse= # XXX: Disable mouse (set by defaults.vim). Needed by macos terminal app.
set number # line numbering
set relativenumber
set hls # highlight search
set lbr # line break
set hidden # buffer becomes hidden (not unloaded) when it is abandoned (ex. help buffer)
set nojoinspaces # suppress inserting two spaces between sentences
set shortmess+=I # disable startup message
set report=0 # suppress reporting number of lines changed
set showmatch # show matching braces when cursor is over them
set ignorecase # case-insensitive search
set smartcase # smart search
set infercase # when doing <c-n/p> completion, respect case
set splitbelow # open new split panes to right
set splitright # open new split panes to bottom
set breakindent # wrapped line will continue visually indented
set smarttab
set spellsuggest=best,10 # set maximum number of suggestions listed top 10 items:
set foldmethod=indent
set foldnestmax=1
set nofoldenable # do not do folding when you open file
set signcolumn=yes # always show column for lsp diagnostics etc
set complete-=i # disable completing keywords from included files (e.g., #include in C)
set dictionary+=/usr/share/dict/words
set whichwrap+=<,>,h,l # make arrows and h, l, push cursor to next line
# set pumheight=7 # max number of items in popup menu (pmenu)
set virtualedit=block # allows selection of rectangular text in visual block mode
set wildignore+=.gitignore,*.swp,*.zwc,tags
set path=.,,
set laststatus=2 # always show statusline
# set laststatus=0
# set rulerformat=%80(%=%f\ %h%m%r\ %-6y\ %-5.(%l,%c%V%)\ %P%)
set cursorline
set textwidth=79
# {{{
# enable colorcolumn for all filetype, but quickfix and help
  set colorcolumn=81
  au FileType qf,help setlocal colorcolumn=
# }}}
set cc=+1
set nowrap
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
set re=1
#set updatetime=1000 # reducing updatetime
set dir=~/tmp
set t_Co=256
set cmdheight=2
set lazyredraw
# set maximum amount of memory (in Kbyte) to use for pattern matching
set mmp=2000000

syntax on # turn on syntax highlighting

# This loads the "matchit" plugin; It makes the % command more powerful, but
# bracket matching gets much slower. Vim's default bracket matching does not
# avoid commented brackets through. and this plugin avoids that.
if has('syntax') && has('eval')
    packadd! matchit
endif

# Suppress netrw banner
# g:netrw_banner = 0

# Disable this when not debugging Vim (:h :Termdebug)
packadd! termdebug
if v:version >= 901 && !getcompletion('comment', 'packadd')->empty()
    packadd comment
endif

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------
#
if &compatible
  # `:set nocp` has many side effects. Therefore this should be done
  # only when 'compatible' is set.
  set nocompatible
endif

packadd minpac

call minpac#init()

call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add('yegappan/lsp')
call minpac#add('machakann/vim-sandwich')

# coverage plugins
# ----------------------------------------------------------------------

# call minpac#add('google/vim-maktaba')
# call minpac#add('google/vim-coverage')
# call minpac#add('google/vim-glaive')
# call minpac#add('some00/vimgcov')
