#! /bin/sh

#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc rule -a '*' state=tiled

external_monitor=$(xrandr | awk '/connected/ && /[[:digit:]]x[[:digit:]].*+/{print $1}')
top_monitor=$external_monitor | grep -w "DP-2-1"
left_monitor=$external_monitor | grep -w "DP-2-2"

ENABLE_EXT=false

if [[ $ENABLE_EXT -eq true ]]; then
  if ! [[ -z $top_monitor ]] || ! [[ -z $left_monitor ]]; then
    comm=""
    if ! [[ -z $top_monitor ]]; then
      comm="$comm --output DP-2-2 --rotate left --left-of eDP-1"
    fi
    if ! [[ -z $top_monitor ]]; then
      comm="$comm --output DP-2-1 --right-of eDP-1"
    fi
    comm="xrandr --output eDP-1 --auto $comm"
    xrandr $comm
  fi
else
  if ! [[ -z $top_monitor ]]; then
    xrandr --output DP-2-1 --off
  fi
  if ! [[ -z $left_monitor ]]; then
    xrandr --output DP-2-2 --off
  fi
  xrandr --output eDP-1 --auto
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

# Truncate a couple of common commands that are used herein.
_bc() {
  bspc config "$@"
}

#### BSPWM configuration ####
_bc window_gap                    12
_bc top_padding                   26
_bc top_monocle_padding           0
_bc border_width                  2
_bc bottom_padding                26
_bc left_padding                  0
_bc right_padding                 0
_bc single_monocle                false
_bc click_to_focus                false
_bc split_ratio                   0.50
_bc borderless_monocle            true
_bc gapless_monocle               true
_bc focus_by_distance             true
_bc paddingless_monocle           true
_bc focus_follows_pointer         true
_bc ignore_ewmh_focus             true
_bc history_aware_focus           true
_bc remove_disabled_monitors      true
_bc remove_unplugged_monitors     true
_bc merge_overlapping_monitors    true
_bc pointer_follows_monitor       true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner
_bc normal_border_color  "#2a2f33"    #"#2a2f33"
_bc focused_border_color "#3F464B"    #"#3F464B"
_bc urgent_border_color  "#83a598"
_bc presel_border_color  "#d3869b"

#### Programs start ####
#bspc rule -a firefox -o desktop=^1
#bspc rule -a discord -o desktop=^2

xsetroot -cursor_name left_ptr &
sxhkd &
picom --config /home/splinter1984/.config/picom/picom.conf &
exec ssh-agent &
pamixer --start &
feh --bg-center ~/Pictures/cdds.png &
~/.config/polybar/launch.sh
