
[window]
dimensions = { columns = 205, lines = 60 }
padding = { x = 4, y = 3 }
decorations = "None"

[font]
normal = { family = "HackNerdFontMono" }
size = 11.0

[cursor]
style = { shape="Block", blinking="On" }
vi_mode_style = { shape="Block", blinking="On" }

[terminal.shell]
program = "/usr/local/bin/tmux"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[general]
import = [
  "custom.toml"
]

[terminal]
#renderer = "Glsl3" 
#render_timer = true
