# ==============================================================================
# Base on:         tomorrow_night.toml
#                  - https://github.com/alacritty/alacritty-theme
#                  papercolor-theme
#                  - https://github.com/NLKNguyen/papercolor-theme
# Last Change:     Oct 21, 2025
# ==============================================================================

# Default colors
[colors.primary]
background = '#121212'
foreground = '#d0d0d0'
# background = '#191919'
# foreground = '#cccccc'
# background = '#1c1c1c'
# foreground = '#d0d0d0'

[colors.cursor]
text = '#1d1f21'
cursor = '#f19618'

# Normal colors
[colors.normal]
black   = '#212121'
red     = '#d54e53'
green   = '#b9ca4a'
yellow  = '#e6c547'
blue    = '#7aa6da'
magenta = '#c397d8'
cyan    = '#70c0ba'
white   = '#424242'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#e7c547'
blue    = '#7aa6da'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#2a2a2a'
